services:
  - type: web
    name: dash-valuation-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app.server
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.12 