services:
  - type: web
    name: dash-valuation-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --workers 1 --bind 0.0.0.0:$PORT app:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.12 